In [72]:
import pandas as pd
import numpy as np


df = pd.read_csv("./training_dataset.csv", encoding='cp1252')



In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6662 entries, 0 to 6661
Data columns (total 32 columns):
OBS_ID                   6662 non-null int64
KANAL                    6662 non-null int64
SHOW_ID                  6662 non-null int64
FAKTOR                   6662 non-null float64
WORDING_ID               6662 non-null int64
BRAND_FLG                6662 non-null int64
BRAND_ID                 6662 non-null float64
WDHL_FLG                 6662 non-null int64
BESTELL_ID               6662 non-null int64
ARTIKEL_ID               6662 non-null int64
SHOW_POSITION            6662 non-null int64
NEW_ITEM_FLG             6662 non-null int64
AIRING_23_FLG            6662 non-null int64
AIRING_456_FLG           6662 non-null int64
ADT_FLG                  6662 non-null int64
WG_ID                    6662 non-null int64
WGH1_ID                  6662 non-null int64
WGH3_ID                  6662 non-null int64
PREIS_DISCOUNT           6662 non-null float64
ANZ_ARTIKEL_ID           6662 no

In [74]:
# calculate correlation between SOLD_OUT_FLG and all other variables

correlations_data = df.corr()['SOLD_OUT_FLG'].sort_values()
print(correlations_data)

ValueError: Format specifier missing precision

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

corr = df.corr()
print(corr)

fig, ax = plt.subplots(figsize=(30,30))         # Sample figsize in inches


sns.heatmap(corr, 
        xticklabels=corr.columns,
        yticklabels=corr.columns, annot=True, linewidths=.5, ax=ax)

In [75]:
x = df

In [76]:
def corr_df(x, corr_val):
    '''
    Obj: Drops features that are strongly correlated to other features.
          This lowers model complexity, and aids in generalizing the model.
    Inputs:
          df: features df (x)
          corr_val: Columns are dropped relative to the corr_val input (e.g. 0.8)
    Output: df that only includes uncorrelated features
    '''

    # Creates Correlation Matrix and Instantiates
    corr_matrix = x.corr()
    iters = range(len(corr_matrix.columns) - 1)
    drop_cols = []

    # Iterates through Correlation Matrix Table to find correlated columns
    for i in iters:
        for j in range(i):
            item = corr_matrix.iloc[j:(j+1), (i+1):(i+2)]
            col = item.columns
            row = item.index
            val = item.values
            if val >= corr_val:
                # Prints the correlated feature set and the corr val
                print(col.values[0], "|", row.values[0], "|", round(val[0][0], 2))
                drop_cols.append(i)

    drops = sorted(set(drop_cols))[::-1]

    # Drops the correlated columns
    for i in drops:
        col = x.iloc[:, (i+1):(i+2)].columns.values
        df = x.drop(col, axis=1)

    return df

In [77]:
df = corr_df(df, 0.6)

SHOW_ID | OBS_ID | 0.91
BESTELL_ID | OBS_ID | 0.7
BESTELL_ID | SHOW_ID | 0.8
ARTIKEL_ID | OBS_ID | 0.7
ARTIKEL_ID | SHOW_ID | 0.8
WGH3_ID | WG_ID | 1.0
PREIS_LABEL_DESC | PREIS_DISCOUNT | 0.7


In [78]:
df.drop(["BESTELL_ID","ARTIKEL_ID","WG_ID","WGH1_ID","PREIS_LABEL_DESC"],axis=1,inplace=True)

In [89]:
#features = df[["PREIS_DISCOUNT","KANAL","FAKTOR","NEW_ITEM_FLG","MENGE_ECOM",
 #              "MENGE_CALL","WGH3_DESC",
  #            "AIRING_23_FLG","ADT_FLG","ONAIR_SEKUNDEN","MENGE_FREI_SHOWBEGINN"]]
features.info()
features.to_excel('hahahahha.xlsx')


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6662 entries, 0 to 6661
Data columns (total 11 columns):
PREIS_DISCOUNT           6662 non-null float64
KANAL                    6662 non-null int64
FAKTOR                   6662 non-null float64
NEW_ITEM_FLG             6662 non-null int64
MENGE_ECOM               6662 non-null float64
MENGE_CALL               6662 non-null float64
WGH3_DESC                6662 non-null int64
AIRING_23_FLG            6662 non-null int64
ADT_FLG                  6662 non-null int64
ONAIR_SEKUNDEN           6662 non-null int64
MENGE_FREI_SHOWBEGINN    6662 non-null int64
dtypes: float64(4), int64(7)
memory usage: 572.6 KB


In [56]:
from sklearn.model_selection import train_test_split

# Separate out the features and targets
features = df[["PREIS_DISCOUNT","KANAL","FAKTOR","NEW_ITEM_FLG","MENGE_ECOM",
               "MENGE_CALL","WGH3_DESC",
              "AIRING_23_FLG","ADT_FLG","ONAIR_SEKUNDEN","MENGE_FREI_SHOWBEGINN"]]
targets = df[['SOLD_OUT_FLG']].astype('category')

# Split into 70% training and 30% testing set
X, X_test, y, y_test = train_test_split(features, targets, test_size = 0.2, random_state = 42)

print(X.shape)
print(X_test.shape)
print(y.shape)
print(y_test.shape)

(5329, 11)
(1333, 11)
(5329, 1)
(1333, 1)


In [57]:
targets.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6662 entries, 0 to 6661
Data columns (total 1 columns):
SOLD_OUT_FLG    6662 non-null category
dtypes: category(1)
memory usage: 6.7 KB


In [58]:
# Save the training, and testing data
X.to_csv('./training_features.csv', index = False)
X_test.to_csv('./testing_features.csv', index = False)
y.to_csv('./training_labels.csv', index = False)
y_test.to_csv('./testing_labels.csv', index = False)

In [59]:
# Read in data into dataframes 
train_features = pd.read_csv('./training_features.csv')
test_features = pd.read_csv('./testing_features.csv')
train_labels = pd.read_csv('./training_labels.csv')
test_labels = pd.read_csv('./testing_labels.csv')

# Display sizes of data
print('Training Feature Size: ', train_features.shape)
print('Testing Feature Size:  ', test_features.shape)
print('Training Labels Size:  ', train_labels.shape)
print('Testing Labels Size:   ', test_labels.shape)

Training Feature Size:  (5329, 11)
Testing Feature Size:   (1333, 11)
Training Labels Size:   (5329, 1)
Testing Labels Size:    (1333, 1)


In [60]:
train_labels = train_labels[['SOLD_OUT_FLG']].astype('category')
test_labels = test_labels[['SOLD_OUT_FLG']].astype('category')

In [61]:
test_labels.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1333 entries, 0 to 1332
Data columns (total 1 columns):
SOLD_OUT_FLG    1333 non-null category
dtypes: category(1)
memory usage: 1.5 KB


In [62]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
# Fit on the training data
scaler.fit(X)

# Transform both the training and testing data
X = scaler.transform(X)
X_test = scaler.transform(X_test)

In [63]:
testing = pd.read_csv("./test_dataset.csv", encoding='cp1252')

testing.drop(["BESTELL_ID","ARTIKEL_ID","WG_ID","WGH1_ID","PREIS_LABEL_DESC"],axis=1,inplace=True)


In [64]:
testing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1003 entries, 0 to 1002
Data columns (total 27 columns):
OBS_ID                   1003 non-null int64
KANAL                    1003 non-null int64
SHOW_ID                  1003 non-null int64
FAKTOR                   1003 non-null float64
WORDING_ID               1003 non-null int64
BRAND_FLG                1003 non-null int64
BRAND_ID                 1003 non-null float64
WDHL_FLG                 1003 non-null int64
SHOW_POSITION            1003 non-null int64
NEW_ITEM_FLG             1003 non-null int64
AIRING_23_FLG            1003 non-null int64
AIRING_456_FLG           1003 non-null int64
ADT_FLG                  1003 non-null int64
WGH3_ID                  1003 non-null int64
PREIS_DISCOUNT           1003 non-null float64
ANZ_ARTIKEL_ID           1003 non-null int64
ONAIR_SEKUNDEN           1003 non-null int64
MENGE_CALL               1003 non-null float64
MENGE_ECOM               1003 non-null float64
WG_DESC                  100

In [65]:
xtest = testing[["PREIS_DISCOUNT","KANAL","FAKTOR","NEW_ITEM_FLG","MENGE_ECOM",
               "MENGE_CALL","WGH3_DESC",
              "AIRING_23_FLG","ADT_FLG","ONAIR_SEKUNDEN","MENGE_FREI_SHOWBEGINN"]]

In [66]:
from sklearn.linear_model import LogisticRegression

LR = LogisticRegression()

LR.fit(X, y)

print(LR.score(X_test, y_test))
# print(model.score(X_training, y_training)) 
# shows how many percent of the dataset was predicted correctly

y_pred = LR.predict(X_test)

from sklearn.metrics import matthews_corrcoef

matthews_corrcoef(y_test, y_pred)

0.9099774943735934


/Users/floriansonneck/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.7521468238335445

In [67]:
y_predictionLR = LR.predict(xtest)

print(y_predictionLR)


#SOLD_OUT_FLG = pd.DataFrame(data=y_predictionLR,columns=['SOLD_OUT_FLG'])
#pred_final=pd.concat([testing['OBS_ID'],SOLD_OUT_FLG],axis =1)
#pred_final.to_csv('sold_out_predict.csv',index=False)

print(sum(y_predictionLR))

[0. 0. 0. ... 0. 0. 0.]
0.0


In [68]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(criterion = "entropy", n_estimators = 15)
classifier.fit(X, y)

print(classifier.score(X_test, y_test))

y_pred = classifier.predict(X_test)

matthews_corrcoef(y_test, y_pred)

0.8799699924981246


/Users/floriansonneck/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


0.6485778316764522

In [69]:
y_predClassifier = classifier.predict(xtest)

# y_predClassifier = np.round(classifier.predict(xtest))


print(y_predClassifier)

shs = y_predClassifier
# np.int_(shs)
# print(shs)
q = shs.astype(int)
print(q)



SOLD_OUT_FLG = pd.DataFrame(data=y_predClassifier,columns=['SOLD_OUT_FLG'])
pred_final=pd.concat([testing['OBS_ID'],SOLD_OUT_FLG],axis =1)
pd.options.display.float_format = '{:,.f}'.format
pred_final.to_csv('sold_out_predict.csv',index=False)



print(sum(y_predClassifier))

[1. 1. 1. ... 1. 1. 1.]
[1 1 1 ... 1 1 1]
573.0
